name: rush
description: rush package for handling responsive screens.
version: 0.0.1
publish_to: none
homepage: https://github.com/khaledSayedAbdellah/rush.git

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
